<?php
/** @var \Magento\Backend\Block\Template $block */
?>
<div class="page-actions">
    <div class="page-actions-inner">
        <div class="page-actions-buttons">
            <a href="<?= $block->escapeUrl($block->getUrl('*/*/status')) ?>"
               class="action action-advanced-reports"
               data-index="analytics-service-link"
               title="<?= $block->escapeHtmlAttr(__('Go to Advanced Reporting')) ?>">
                <span><?= $block->escapeHtml(__('Go to Advanced Reporting')) ?></span>
            </a>
        </div>
    </div>
</div>
